name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
#  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^1.23.0
#  firebase_auth: ^3.3.20
  firebase_crashlytics: ^2.8.11
#  firebase_performance: ^0.7.1+5
#  firebase_remote_config: ^1.0.2

  # For Firebase Cloud Messaging
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1

  # For Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4

  # For Networking
  dio: ^4.0.6
#  dio_firebase_performance: ^0.3.0
  retrofit: ^3.0.1+1
  # For User-Agent Client Hints
  ua_client_hints: ^1.1.2

  # For Model
  json_serializable: ^6.2.0
  freezed_annotation: ^2.0.3

  # For save data local
  shared_preferences: ^2.0.15

  # For DateTime
  intl: ^0.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For route
  auto_route: ^4.0.1

  # For UIs
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.2
  flutter_screenutil: ^5.5.4

  # For querying information about an application package.
  package_info_plus: ^1.4.3+1

  # For launching url
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11

  # For Networking
  retrofit_generator: ^4.0.1

  # For Assets
  flutter_gen_runner: ^4.1.2
  # auto_route and freezed version conflict
  # For Model
  freezed: ^2.0.3+1

  # For Analyzer
  flutter_lints: ^2.0.1

  # For AutoRoute
  auto_route_generator: ^4.0.0

  # For Testing
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

  # For change package name quickly
  change_app_package_name: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
