name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
#  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^1.23.0
#  firebase_auth: ^3.3.20
  firebase_crashlytics: ^2.8.11
#  firebase_performance: ^0.7.1+5
#  firebase_remote_config: ^1.0.2

  # Firebase Cloud Messaging
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1

  # Architecture
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2

  # Networking
  dio: ^4.0.6
#  dio_firebase_performance: ^0.3.0
  retrofit: ^3.3.1
  # User-Agent Client Hints
  ua_client_hints: ^1.1.2

  # Model
  json_serializable: ^6.5.1
  freezed_annotation: ^2.0.3

  # save data local
  shared_preferences: ^2.0.15

  # DateTime
  intl: ^0.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # route
  auto_route: ^5.0.1

  # UIs
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.2
  flutter_screenutil: ^5.5.4

  # querying information about an application package.
  package_info_plus: ^1.4.3+1

  # launching url
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.0

  # Networking
  retrofit_generator: ^4.2.0

  # Assets
  flutter_gen_runner: ^5.0.2
  # auto_route and freezed version conflict
  # Model
  freezed: ^2.0.3+1

  # Analyzer
  flutter_lints: ^2.0.1

  # AutoRoute
  auto_route_generator: ^5.0.2

  # Testing
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

  # change package name quickly
  change_app_package_name: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
